### ISSUE TITLE
permission denied to run jupyter on mox

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1511]
I've followed the instructions in the handbook ([here](https://robertslab.github.io/resources/mox_Jupyter-Notebooks/)). 

### Permission denied - can I get permission? 

Code and output below in case something is wrong there: 

```
[graceac9@mox1 ~]$ srun -p srlab --time=2:00:00 --pty /bin/bash
srun: job 3466180 queued and waiting for resources
srun: job 3466180 has been allocated resources
[graceac9@n2193 ~]$ module load anaconda2_4.3.1:
ERROR: Unable to locate a modulefile for 'anaconda2_4.3.1:'
[graceac9@n2193 ~]$ module load anaconda2_4.3.1
[graceac9@n2193 ~]$ jupyter notebook --no-browser --port=8899
/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/cffi/model.py:532: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/sw/anaconda-4.3.1/python2/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1140, in initialize
    self.init_configurables()
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/notebook/notebookapp.py", line 901, in init_configurables
    connection_dir=self.runtime_dir,
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/sw/anaconda-4.3.1/python2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/run/user/442057'
```

**Comment by kubu4** [comment]
I don't think that works any more. It'll be much easier to use screen sharing via Ostrich if you want to use a Jupyter Notebook.

**Comment by sr320** [comment]
Handbook should be updated accordingly

**Comment by kubu4** [comment]
@grace-ac - I've updated the Handbook with instructions that will allow you to run Jupyter Notebook on Mox.

Please give them a shot when you have a sec and let me know at which steps you get stuck (I know there are likely at least two spots that will result in errors).

**Comment by sr320** [comment]
Note I would personally would not recommend running Jupyter on mox and go with ostrich as Sam recommends ...
@grace-ac what is your use case?

**Comment by sr320** [comment]
I do not necessarily recommend running Jupyter on mox. What is the
rationale / reasoning?
